eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**

        - id: agences
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/agences/**

        - id: medias
          uri: http://localhost:8016
          predicates:
            - Path=/api/v1/medias/**

    discovery:
      enabled: true
    config:
      enabled: false



