eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/users/**

        - id: agences
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/agences/**

        - id: medias
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/medias/**

        - id: immeubles
          uri: http://localhost:8187
          predicates:
            - Path=/api/v1/immeubles/**

        - id: appartements
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/appartements/**
        - id: travaux
          uri: http://localhost:8097
          predicates:
            - Path=/api/v1/travaux/**

        - id: plaintes
          uri: http://localhost:8098
          predicates:
            - Path=/api/v1/plaintes/**

        - id: evenements
          uri: http://localhost:8099
          predicates:
            - Path=/api/v1/evenements/**

        - id: annonces
          uri: http://localhost:9000
          predicates:
            - Path=/api/v1/annonces/**

        - id: contrats
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/contrats/**

    discovery:
      enabled: true
    config:
      enabled: false



