eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: users
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: login
          uri: http://localhost:8085
          predicates:
            - Path=/login


        - id: agences
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/agences/**
          filters:
            - AuthenticationFilter

        - id: medias
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/medias/**
          filters:
            - AuthenticationFilter

        - id: notifications
          uri: http://localhost:8111
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AuthenticationFilter

        - id: immeubles
          uri: http://localhost:8187
          predicates:
            - Path=/api/v1/immeubles/**
          filters:
            - AuthenticationFilter

        - id: appartements
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/appartements/**
          filters:
            - AuthenticationFilter

        - id: travaux
          uri: http://localhost:8097
          predicates:
            - Path=/api/v1/travaux/**
          filters:
            - AuthenticationFilter

        - id: plaintes
          uri: http://localhost:8098
          predicates:
            - Path=/api/v1/plaintes/**
          filters:
            - AuthenticationFilter

        - id: evenements
          uri: http://localhost:8099
          predicates:
            - Path=/api/v1/evenements/**
          filters:
            - AuthenticationFilter

        - id: annonces
          uri: http://localhost:9000
          predicates:
            - Path=/api/v1/annonces/**
          filters:
            - AuthenticationFilter

        - id: contrats
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/contrats/**
          filters:
            - AuthenticationFilter

        - id: payment-syndecals
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/payment-syndecals/**
          filters:
            - AuthenticationFilter

        - id: payment-contrat-ventes
          uri: http://localhost:9003
          predicates:
            - Path=/api/v1/payment-contrat-ventes/**
          filters:
            - AuthenticationFilter

        - id: payment-contrat-loyers
          uri: http://localhost:9003
          predicates:
            - Path=/api/v1/payment-contrat-loyers/**
          filters:
            - AuthenticationFilter

    discovery:
      enabled: true
    config:
      enabled: false



