eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/users/**

        - id: agences
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/agences/**

        - id: medias
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/medias/**

        - id: immeubles
          uri: http://localhost:8187
          predicates:
            - Path=/api/v1/immeubles/**

        - id: appartements
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/appartements/**
    discovery:
      enabled: true
    config:
      enabled: false



