server:
  port: 8085
spring:
  application:
    name: users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1234/darkom
    username: postgres
    password: 1111
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: maromouslih@gmail.com
    password: agznniyauptyizvh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
